format = """
[](nord10)\
$username[@](bg:nord10 fg:nord3)$hostname\
[](bg:nord9 fg:nord10)\
$directory\
[](bg:nord4 fg:nord9)\
$git_branch$git_commit$git_state$git_metrics$git_status\
[](fg:nord4)\
$fill\
$dotnet\
$nodejs\
$line_break\
$character
"""

palette = 'nord'

[username]
show_always = true
style_user = "bg:nord10 fg:nord0"
format = '[$user]($style)'

[hostname]
ssh_only = false
style = "bg:nord10 fg:nord0"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = " "

[directory]
style = "fg:nord0 bg:nord9"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[character]
success_symbol = '[⤷](bold nord14) '
error_symbol = '[⤷](bold nord11) '

[fill]
symbol = ' '

### Git

[git_branch]
symbol = ""
style = "bg:nord4"
format = '[[ $symbol $branch ](fg:nord0 bg:nord4)]($style)'

[git_status]
style = "bg:nord4"
format = '[[($all_status$ahead_behind )](fg:nord0 bg:nord4)]($style)'

### Languages

[nodejs]
symbol = ""
style = "bg:nord7"
format = '[[ $symbol ($version) ](fg:nord0 bg:nord7)]($style)'

[dotnet]
style = "fg:nord4"
format = '[[ $symbol($version)](fg:nord4 )]($style)'

### Colors

[palettes.nord]
# Base component color of "Polar Night".
#
# Used for texts, backgrounds, carets and structuring characters like curly- and square brackets.
#
# Markup:
# <div style="background-color:#2e3440; width=60; height=60"></div>
#
# Styleguide Nord - Polar Night
nord0 = "#2e3440"

# Lighter shade color of the base component color.
#
# Used as a lighter background color for UI elements like status bars.
nord1 = "#3b4252"

# Lighter shade color of the base component color.
#
# Used as line highlighting in the editor.
# In the UI scope it may be used as selection- and highlight color.
nord2 = "#434c5e"

# Lighter shade color of the base component color.
#
# Used for comments, invisibles, indent- and wrap guide marker.
# In the UI scope used as pseudoclass color for disabled elements.
nord3 = "#4c566a"

# Base component color of "Snow Storm".
#
# Main color for text, variables, constants and attributes.
# In the UI scope used as semi-light background depending on the theme shading design.
nord4 = "#d8dee9"

# Lighter shade color of the base component color.
#
# Used as a lighter background color for UI elements like status bars.
# Used as semi-light background depending on the theme shading design.
nord5 = "#e5e9f0"

# Lighter shade color of the base component color.
#
# Used for punctuations, carets and structuring characters like curly- and square brackets.
# In the UI scope used as background, selection- and highlight color depending on the theme shading design.
nord6 = "#eceff4"

# Bluish core color.
#
# Used for classes, types and documentation tags.
nord7 = "#8fbcbb"

# Bluish core color.
#
# Represents the accent color of the color palette.
# Main color for primary UI elements and methods/functions.
#
# Can be used for
#   - Markup quotes
#   - Markup link URLs
nord8 = "#88c0d0"

# Bluish core color.
#
# Used for language-specific syntactic/reserved support characters and keywords, operators, tags, units and
# punctuations like (semi)colons,commas and braces.
nord9 = "#81a1c1"

# Bluish core color.
#
# Used for markup doctypes, import/include/require statements, pre-processor statements and at-rules (`@`).
nord10 = "#5e81ac"

# Colorful component color.
#
# Used for errors, git/diff deletion and linter marker.
nord11 = "#bf616a"

# Colorful component color.
#
# Used for annotations.
nord12 = "#d08770"

# Colorful component color.
#
# Used for escape characters, regular expressions and markup entities.
# In the UI scope used for warnings and git/diff renamings.
nord13 = "#ebcb8b"

# Colorful component color.
#
# Main color for strings and attribute values.
# In the UI scope used for git/diff additions and success visualizations.
nord14 = "#a3be8c"

# Colorful component color.
#
# Used for numbers.
nord15 = "#b48ead"
